/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadRouteImport } from './routes/actividad'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as ComidaRouteImport } from './routes/comida'
import { Route as TendenciasRouteImport } from './routes/tendencias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadRoute = ActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComidaRoute = ComidaRouteImport.update({
  id: '/comida',
  path: '/comida',
  getParentRoute: () => rootRouteImport,
} as any)
const TendenciasRoute = TendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/comida': typeof ComidaRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/comida': typeof ComidaRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/comida': typeof ComidaRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/actividad' | '/ajustes' | '/comida' | '/tendencias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actividad' | '/ajustes' | '/comida' | '/tendencias'
  id: '__root__' | '/' | '/actividad' | '/ajustes' | '/comida' | '/tendencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadRoute: typeof ActividadRoute
  AjustesRoute: typeof AjustesRoute
  ComidaRoute: typeof ComidaRoute
  TendenciasRoute: typeof TendenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad': {
      id: '/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof ActividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comida': {
      id: '/comida'
      path: '/comida'
      fullPath: '/comida'
      preLoaderRoute: typeof ComidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendencias': {
      id: '/tendencias'
      path: '/tendencias'
      fullPath: '/tendencias'
      preLoaderRoute: typeof TendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadRoute: ActividadRoute,
  AjustesRoute: AjustesRoute,
  ComidaRoute: ComidaRoute,
  TendenciasRoute: TendenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
